codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
    patch: yes
    changes: no

ignore:
  - "src/main/java/seedu/address/ui/.*"  # Ignores all files in the UI folder
  - "src/test/java/seedu/address/ui/.*"  # Also ignore UI tests

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
