name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      - name: Install xvfb for Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xvfb

      - name: Build and check with Gradle (Linux)
        if: runner.os == 'Linux'
        run: |
          xvfb-run --server-args="-screen 0 1024x768x24" ./gradlew check coverage \
          --no-daemon \
          -Porg.gradle.jvmargs="--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui.delegate=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui.monocle=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED"

      - name: Build and check with Gradle (Non-Linux)
        if: runner.os != 'Linux'
        run: |
          ./gradlew check coverage \
          --no-daemon \
          -Porg.gradle.jvmargs="--add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui.delegate=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.ui.monocle=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED \
          --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED"
          
      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
