name: Java CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Set up repository
        uses: actions/checkout@main

      - name: Set up repository
        uses: actions/checkout@main
        with:
          ref: master

      - name: Merge to master
        run: git checkout --progress --force ${{ github.sha }}

      - name: Run repository-wide tests
        if: runner.os == 'Linux'
        working-directory:  ${{ github.workspace }}/.github
        run: ./run-checks.sh

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk+fx

      # Add Gradle caching
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install xvfb for Linux
        if: runner.os == 'Linux'
        run: sudo apt-get install -y xvfb

      # Clear Gradle cache and refresh dependencies
      - name: Clean and refresh dependencies
        run: |
          ./gradlew clean
          ./gradlew --stop
          ./gradlew --refresh-dependencies

      - name: Build and check with Gradle (Linux)
        if: runner.os == 'Linux'
        env:
          DISPLAY: ':99.0'
          JAVA_OPTS: '-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500'
          _JAVA_OPTIONS: >-
            --add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui.delegate=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui.monocle=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
            --add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED
            --add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.sg.prism=ALL-UNNAMED
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          sleep 3
          ./gradlew check coverage --info

      - name: Build and check with Gradle (Non-Linux)
        if: runner.os != 'Linux'
        env:
          JAVA_OPTS: '-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500'
          _JAVA_OPTIONS: >-
            --add-exports=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui.delegate=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.ui.monocle=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.glass.utils=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.application=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.tk=ALL-UNNAMED
            --add-opens=javafx.controls/javafx.scene.control=ALL-UNNAMED
            --add-opens=javafx.graphics/javafx.scene=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.scene=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.scene.traversal=ALL-UNNAMED
            --add-opens=javafx.graphics/com.sun.javafx.sg.prism=ALL-UNNAMED
        run: ./gradlew check coverage --info

      - name: Upload coverage reports to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
